### ISSUE TITLE
PackageManagement module path does not meet PowerShell standards

### ISSUE THREAD

**Issue by lfshr** [big-data-for-humans/azure-automation-tools#11]
Powershell standards dictates that the root folder of a module should have the exact same name as the filename of the psd1 file. Currently the root folder of packagemanagement is 'PackageManagement' and the filename is 'AzureAutomationTools.PackageManagement' Either the psd1 file or the path should change it's name.

**Comment by stvnrs** [comment]
You are confusing the source setup (modeled on official Microsoft projects)
and the deployment of the module - the build  creates a folder with the
same name as the module so that it deployed in line with powershell
convention

**Comment by lfshr** [comment]
My mistake 😞
